name       : libxinerama
version    : 1.1.3
release    : 9
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXinerama-1.1.3.tar.bz2 : 7a45699f1773095a3f821e491cbd5e10c887c5a5fce5d8d3fced15c2ff7698e2
license    : MIT
summary    : X Xinerama extension library
component  : xorg.library
description: |
    libXinerama provides an X Window System client interface to the XINERAMA extension to the X protocol.
builddeps  :
    - pkgconfig(xineramaproto)
    - pkgconfig32(x11)
    - pkgconfig32(xext)
emul32     : yes
optimize   : speed
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
