name       : libxinerama
version    : 1.1.4
release    : 15
source     :
    - https://www.x.org/releases/individual/lib/libXinerama-1.1.4.tar.gz : 64de45e18cc76b8e703cb09b3c9d28bd16e3d05d5cd99f2d630de2d62c3acc18
license    : MIT
summary    : X Xinerama extension library
component  : xorg.library
description: |
    libXinerama provides an X Window System client interface to the XINERAMA extension to the X protocol.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(x11)
    - pkgconfig32(xext)
    - pkgconfig(xproto)
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
